INSERT INTO SKILLS (id, freelancer_id, skill_name, proficiency_level, years_experience) VALUES
(1, 1, 'React', 'EXPERT', 5),
(2, 1, 'Node.js', 'EXPERT', 5),
(3, 1, 'PostgreSQL', 'INTERMEDIATE', 4),
(4, 1, 'TypeScript', 'INTERMEDIATE', 3),
(5, 1, 'AWS', 'BEGINNER', 2),
(6, 2, 'Figma', 'EXPERT', 6),
(7, 2, 'Adobe XD', 'EXPERT', 5),
(8, 2, 'UI Design', 'EXPERT', 6),
(9, 2, 'UX Research', 'INTERMEDIATE', 4),
(10, 2, 'Prototyping', 'EXPERT', 5),
(11, 3, 'SEO Writing', 'EXPERT', 7),
(12, 3, 'Content Strategy', 'INTERMEDIATE', 5),
(13, 3, 'Copywriting', 'EXPERT', 6),
(14, 3, 'WordPress', 'INTERMEDIATE', 4),
(15, 3, 'Technical Writing', 'INTERMEDIATE', 3),
(16, 4, 'Python', 'EXPERT', 8),
(17, 4, 'Machine Learning', 'EXPERT', 6),
(18, 4, 'TensorFlow', 'INTERMEDIATE', 4),
(19, 4, 'Data Visualization', 'EXPERT', 5),
(20, 4, 'SQL', 'EXPERT', 7),
(21, 5, 'Social Media Marketing', 'EXPERT', 6),
(22, 5, 'Google Ads', 'INTERMEDIATE', 5),
(23, 5, 'SEO', 'INTERMEDIATE', 4),
(24, 5, 'Content Marketing', 'EXPERT', 6),
(25, 5, 'Analytics', 'INTERMEDIATE', 4),
(26, 6, 'Swift', 'EXPERT', 7),
(27, 6, 'Kotlin', 'INTERMEDIATE', 5),
(28, 6, 'React Native', 'EXPERT', 4),
(29, 6, 'iOS Development', 'EXPERT', 7),
(30, 6, 'Android Development', 'INTERMEDIATE', 5),
(31, 7, 'Adobe Illustrator', 'EXPERT', 8),
(32, 7, 'Adobe Photoshop', 'EXPERT', 8),
(33, 7, 'Brand Design', 'EXPERT', 7),
(34, 7, 'Logo Design', 'EXPERT', 6),
(35, 7, 'Print Design', 'INTERMEDIATE', 5),
(36, 8, 'AWS', 'EXPERT', 6),
(37, 8, 'Docker', 'EXPERT', 5),
(38, 8, 'Kubernetes', 'EXPERT', 4),
(39, 8, 'CI/CD', 'EXPERT', 5),
(40, 8, 'Linux', 'EXPERT', 8),
(41, 9, 'Adobe Premiere Pro', 'EXPERT', 6),
(42, 9, 'After Effects', 'EXPERT', 5),
(43, 9, 'Motion Graphics', 'EXPERT', 4),
(44, 9, 'Color Grading', 'INTERMEDIATE', 4),
(45, 9, 'Video Editing', 'EXPERT', 6),
(46, 10, 'Solidity', 'EXPERT', 4),
(47, 10, 'Web3.js', 'EXPERT', 3),
(48, 10, 'Smart Contracts', 'EXPERT', 4),
(49, 10, 'Ethereum', 'EXPERT', 4),
(50, 10, 'DeFi', 'INTERMEDIATE', 2);